baseURL = "/"
languageCode = "en-us"


[params]
footerContent= "Copyright 2003-2021 | IJM PH A Blessing From God To All Children"
menuButtonText= "Learn More"
SiteLogo = "/IJM_Logo_Horizontal_White_ForWeb.png"


[[menu.main]]
Name = "About"
url = "/about"


